verbs = "To adjust is a verb. To allow is a verb. To appear is a verb. To approve is a verb. To ask is a verb. To be is a verb. To begin is a verb. To bombard is a verb. To boom is a verb. To break is a verb. To call is a verb. To choke is a verb. To compress is a verb. To consider is a verb. To continue is a verb. To contrast is a verb. To crumble is a verb. To curve is a verb. To decide is a verb. To decorate is a verb. To deposit is a verb. To display is a verb. To do is a verb. To dominate is a verb. To echo is a verb. To emit is a verb. To end is a verb. To ensure is a verb. To evoke is a verb. To fiddle is a verb. To fill is a verb. To gape is a verb. To generate is a verb. To glance is a verb. To grow is a verb. To hand is a verb. To hang is a verb. To have is a verb. To hide is a verb. To hog is a verb. To hope is a verb. To hurt is a verb. To ignore is a verb. To imply is a verb. To indicate is a verb. To intend is a verb. To interject is a verb. To issue is a verb. To keep is a verb. To kick is a verb. To know is a verb. To laugh is a verb. To lie is a verb. To line is a verb. To look is a verb. To lounge is a verb. To mar is a verb. To move is a verb. To mumble is a verb. To muse is a verb. To mutter is a verb. To occupy is a verb. To peel is a verb. To peer is a verb. To perform is a verb. To pierce is a verb. To pop is a verb. To possess is a verb. To pour is a verb. To present is a verb. To prompt is a verb. To read is a verb. To recall is a verb. To recognize is a verb. To reflect is a verb. To remind is a verb. To remove is a verb. To replace is a verb. To reveal is a verb. To run is a verb. To scribble is a verb. To separate is a verb. To shudder is a verb. To sigh is a verb. To sit is a verb. To squint is a verb. To stand is a verb. To stare is a verb. To state is a verb. To stir is a verb. To streak is a verb. To stretch is a verb. To study is a verb. To suggest is a verb. To surround is a verb. To tell is a verb. To think is a verb. To touch is a verb. To try is a verb. To twinkle is a verb. To twitch is a verb. To use is a verb. To wait is a verb. To wake is a verb. To whisper is a verb. To zap is a verb. To rush is a verb. To reach is a verb. To slice is a verb. To rise is a verb."
verbs += " "

verbs = verbs.split(". ")
verbs = [f"{v.strip()}." for v in verbs if len(v.strip())]
verbs = [v for i, v in enumerate(verbs) if v not in verbs[:i]]
verbs.sort()

print(" ".join(verbs))
